// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Color: typeof import('./components/color/index.vue')['default'];
    Footer: typeof import('./components/footer/index.vue')['default'];
    Header: typeof import('./components/Header/index.vue')['default'];
    ProductCard: typeof import('./components/product-card/index.vue')['default'];
    Result: typeof import('./components/result/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default'];
    TAside: typeof import('tdesign-vue')['Aside'];
    TContent: typeof import('tdesign-vue')['Content'];
    TDropdown: typeof import('tdesign-vue')['Dropdown'];
    TDropdownItem: typeof import('tdesign-vue')['DropdownItem'];
    TDropdownMenu: typeof import('tdesign-vue')['DropdownMenu'];
    TFooter: typeof import('tdesign-vue')['Footer'];
    Thumbnail: typeof import('./components/thumbnail/index.vue')['default'];
    TIcon: typeof import('tdesign-vue')['Icon'];
    TLayout: typeof import('tdesign-vue')['Layout'];
    Trend: typeof import('./components/trend/index.vue')['default'];
    TTabPanel: typeof import('tdesign-vue')['TabPanel'];
    TTabs: typeof import('tdesign-vue')['Tabs'];
  }
}

export {};
